BEGIN TRANSACTION FIRST_SCRIPT

CREATE TABLE LOGINS (
    USERNAME varchar(255),
    PASSWORD varchar(255)
);

INSERT INTO LOGINS (USERNAME, PASSWORD)
VALUES ('test','test')

SELECT * FROM LOGINS

--ROLLBACK TRANSACTION FIRST_SCRIPT
COMMIT TRANSACTION FIRST_SCRIPT